aayat = [2, 6, 1, 10, 11, 999, 45, 284, 3, 2]
print(aayat)
aayat.sort()
print(aayat)
aayat.sort(reverse=True)
print(aayat)
aayat.sort(reverse=False)
print(aayat)
print(aayat.index(1))
print(aayat)
aayat.insert(1, 99999)
print(aayat)
h = aayat.copy()
print(h)
# aayat.extend()
print(aayat)
